
data:
  manifest_path: "./Baseline/manifest.csv"
  sample_size: 100 # Set to null (full sample - around 10k) or a number
  mode: "psd" #lc light curve, psd for power spectrum
  target_length: null #if none, assumes 65000 for lc mode, 35000 for psd mode. If a value, assumes that value
  batch_size: 64
  num_workers: 4
  filter_duration: "80d"  # Or null to use all files
  seq_length: 128  # Only used for transformer model, ignored otherwise
  

model:
  type: "cnn" # cnn, mlp, transformer
  learning_rate: 0.0005
  epochs: 50
  loss_function: "huber" # mse, l1, huber
  loss_weights:
    nu: 1.0
    dnu: 0.5

paths:
  checkpoint_dir: "./Baseline/results/checkpoints"